### PR TITLE
Replaced the skeleton loader with a message that no guilds are available

### PR DESCRIPTION
**Pull request by ocielliottc**

### CODE REVIEW

**Comment by mkimberlin** [comment]
@ocielliottc I see where you are coming from on this...but I don't think removing the skeleton loader completely is the way I would address this. I think we should show the skeleton loader when the data is still loading, and display the message only if the response comes back with no guilds.

**Comment by ocielliottc** [comment]
> @ocielliottc I see where you are coming from on this...but I don't think removing the skeleton loader completely is the way I would address this. I think we should show the skeleton loader when the data is still loading, and display the message only if the response comes back with no guilds.

I initially thought that the guilds were requested through an API.  But, they're actually passed into the component.

**Comment by ocielliottc** [comment]
> > @ocielliottc I see where you are coming from on this...but I don't think removing the skeleton loader completely is the way I would address this. I think we should show the skeleton loader when the data is still loading, and display the message only if the response comes back with no guilds.
> 
> I initially thought that the guilds were requested through an API. But, they're actually passed into the component.

Hmm...that's not right.  I'll take a closer look.

**Comment by ocielliottc** [comment]
> > > @ocielliottc I see where you are coming from on this...but I don't think removing the skeleton loader completely is the way I would address this. I think we should show the skeleton loader when the data is still loading, and display the message only if the response comes back with no guilds.
> > 
> > 
> > I initially thought that the guilds were requested through an API. But, they're actually passed into the component.
> 
> Hmm...that's not right. I'll take a closer look.

Ok.  The guilds are actually loaded by the AppContext.  So, I think they're loaded before the guilds page is even loaded.

**Pull request merged**
