### PR TITLE
Fixed Skeleton Loader

### PR DESCRIPTION
**Pull request by thelenw**
This was thought to be an issue specific to the administrator page "Manage Kudos," but was in fact a system-wide issue with the skeleton loader. It has been resolved simply and exclusively within the following file:

check-ins/web-ui/src/components/skeleton_loader/SkeletonLoader.jsx

The changes are available for comparison manually or under the following pull request:

https://github.com/objectcomputing/check-ins/pull/2603

### CODE REVIEW

**Comment by mkimberlin** [comment]
@thelenw looks like this was already implemented in the other branch. I will leave it to you to decide what adjustments are needed to resolve the conflicts and to implement the widening of the skeleton described in the issue

**Comment by thelenw** [comment]
Upon review of this issue it appears that the skeleton pre-loading remains resolved from my changes, and the width of the skeleton also seems appropriate on the Manage Kudos page potentially due to other logged changes. Hereby I resolved a meaningless issue with differences in comments between the branches and committed the merge for testing. Please inform me if there is more work to be done to meet the requirements for this issue; from the documentation I've received it appears resolved.

**Comment by mkimberlin** [comment]
This PR had no changes after update from develop.

**Comment by thelenw** [comment]
To be clear, I completed the issue described here and explained how in the initial comment.

**Comment by thelenw** [comment]
A disagreement about feature implementation between @mkimberlin and myself has been resolved elsewhere to ultimate benefit for the platform. See #2627

**Pull request closed without merging**
