### PR TITLE
feature-1666/view past member checkins with a vengeance

### PR DESCRIPTION
**Pull request by zsbrown97**

### CODE REVIEW

**Review by S78901 — COMMENTED** [review]
This looks pretty good to me.

**Review by pieperm — COMMENTED** [review]
Code looks good, though when I pulled the branch down, I was unable to access anything other than the homepage (and the sidebar was missing)

**Comment by pieperm** [comment]
If I log in as Geetika, "Unreal Ulysses" is displayed twice in the list of former partners. Is this intentional behavior? Also, clicking on former partners only works if Geetika is logged in as an admin, otherwise it says I do not have permission.

check-ins

**Comment by zsbrown97** [comment]
> 

How are you signing in to the program? I never ran into duplicates like that, I'll investigate.

**Review by pieperm — APPROVED** [review]

**Pull request merged**
